const posts = [
  {
    id: 0,
    picture: "python.png",
    title: "Codando em python",
    subtitle: "Como apreender python",
    text: "",
    acessed: 0,
    date: "12/12/2004",
    category: "linguagens",
  },
  {
    id: 1,
    picture: "html5.jpeg",
    title: "HTML5",
    subtitle: "Linguagem de marcação HTML5",
    text: "",
    acessed: 0,
    date: "12/04/2004",
    category: "linguagens",
  },
  {
    id: 2,
    picture: "css.jpeg",
    title: "Css para iniciantes",
    subtitle: "A beleza do css",
    text: "",
    acessed: 0,
    date: "21/04/2004",
    category: "linguagens",
  },
  {
    id: 3,
    picture: "javascript.jpeg",
    title: "Javascript dinamico",
    subtitle: "Javascript",
    text: "",
    acessed: 0,
    date: "12/12/2005",
    category: "linguagens",
  },
  {
    id: 4,
    picture: "webdev.jpeg",
    title: "O front-end mais usado",
    subtitle: "Curso de desenvolvedor",
    text: "",
    acessed: 0,
    date: "12/12/2015",
    category: "linguagens",
  },
  {
    id: 5,
    picture: "pc.jpeg",
    title: "Pcs para programadores",
    subtitle: "Pcs para progamar o que procurar?",
    text: "",
    acessed: 0,
    date: "06/06/2016",
    category: "produtos",
  },
  {
    id: 6,
    picture: "Program-Code-Feature-Image.jpg",
    title: "Lógica de progamação",
    subtitle: "Lógica de programação",
    text: "",
    acessed: 0,
    date: "28/02/2016",
    category: "linguagens",
  },
  {
    id: 7,
    picture: "postura.jpg",
    title: "Cadeiras para escritório",
    subtitle: "Revisão de 200 cadeira de escritório",
    text: "",
    acessed: 0,
    date: "12/10/2023",
    category: "produtos",
  },
];
export default posts;
